# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: konrad.jelen@gmail.com
author_name: Stellars Henson
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab_launcher_navigate_to_kernel_extension
project_short_description: Jupyterlab extension to allow user to right-click on the
    kernel launcher button and select 'Show in File Browser' or 'Open Terminal at
    location' menus and get them to navigate to location or open location in terminal
    respectively
python_name: jupyterlab_launcher_navigate_to_kernel_extension
repository: ''
test: true

